name : pytest_and_flake8_controle_push
on: push
jobs:
  qa: 
    name: check_tests
    runs-on: ubuntu-20.04
    steps: 
      - name: checkout_on_master
        uses: actions/checkout@v3

      - name: set_up_python
        uses: actions/setup-python@master
        with:
          python-version: "3.x"

      - name: install_pytest_and_flake8
        run: |
          pip install pytest
          pip install flake8

      - name: run_tests
        run: |
          pytest

      - name: run_flake8
        uses: py-actions/flake8@v2

