name : Pytest & flake8 control Push
on: push
jobs:
  qa: 
    name: check_tests
    runs-on: ubuntu-20-04
steps: 
  - name: cCheckout_on_ master
    uses: actions/checkout@v3

  - name: set_ up_python
    uses: actions/setup-python@master
    with:
      python-version: "3.x"

- name: install_pytest_and_flake8
  run: |
    pip install pytest
    pip install flake8

- name: Run tests
  run: |
    pytest

- name: Run flake8
  uses: py-actions/flake8@v2

